In [ ]:
import pandas as pd
from geopy.geocoders import Nominatim
from time import sleep

In [5]:
df = pd.read_csv("SNAP Member Info - Sheet1.csv")
locations = df[["City", "State"]].dropna().drop_duplicates()

# Split rows where City and State contain "/" into separate rows
split_rows = []
keep_mask = []
for idx, row in locations.iterrows():
    if "/" in str(row["City"]):
        cities = [c.strip() for c in row["City"].split("/")]
        states = [s.strip() for s in row["State"].split("/")]
        for city, state in zip(cities, states):
            split_rows.append({"City": city, "State": state})
        keep_mask.append(False)
    else:
        keep_mask.append(True)

locations = pd.concat(
    [locations[keep_mask], pd.DataFrame(split_rows)],
    ignore_index=True
).drop_duplicates()
locations

               City State
0         Arlington    VA
1         Iowa City    IA
2        Birmingham    Al
3       Chapel Hill    NC
4         Baltimore    MD
5       Los Angeles    CA
6            Athens    GA
7         Cambridge    MA
8            Ithaca    NY
9         New Haven    CT
10         Berkeley    CA
11     Philadelphia    PA
12      Gainesville    FL
13           Denver    CO
14          Seattle    WA
15          Madison    WI
16          Boulder    CO
17    San Francisco    CA
18        St. Louis    MO
19     College Park    MD
20            Miami    FL
21          Detroit    MI
22        Palo Alto    CA
23          Chicago    IL
24          Amherst    MA
25  Charlottesville    VA
26           Newark    DE
27           Durham    NC
28           Boston    MA
29       Huntington    WV
30       South Bend    IN
31           Austin    TX
32             Kent    OH
33          Atlanta    GA
34          Waltham    MA
35         New York    NY
36        Kalamazoo    MI
37     Indianapolis    IN

In [7]:
geolocator = Nominatim(user_agent="snap_member_map")

def get_coords(row):
    query = f"{row['City']}, {row['State']}, USA"
    location = geolocator.geocode(query)
    sleep(1)  # respect Nominatim rate limit
    if location:
        return pd.Series({"lat": location.latitude, "lon": location.longitude})
    return pd.Series({"lat": None, "lon": None})

locations[["lat", "lon"]] = locations.apply(get_coords, axis=1)
locations

               City State        lat         lon
0         Arlington    VA  38.876933  -77.089309
1         Iowa City    IA  41.661256  -91.529911
2        Birmingham    Al  33.520682  -86.802433
3       Chapel Hill    NC  35.913154  -79.055780
4         Baltimore    MD  39.290882  -76.610759
5       Los Angeles    CA  34.053691 -118.242766
6            Athens    GA  33.959768  -83.376398
7         Cambridge    MA  42.365635  -71.104002
8            Ithaca    NY  42.437418  -76.548372
9         New Haven    CT  41.308214  -72.925052
10         Berkeley    CA  37.870839 -122.272863
11     Philadelphia    PA  39.952724  -75.163526
12      Gainesville    FL  29.651968  -82.324985
13           Denver    CO  39.739236 -104.984862
14          Seattle    WA  47.603832 -122.330062
15          Madison    WI  43.074690  -89.384166
16          Boulder    CO  40.014986 -105.270545
17    San Francisco    CA  37.787936 -122.407520
18        St. Louis    MO  38.625406  -90.190009
19     College Park    MD  38.980666  -76.936919
20            Miami    FL  25.774157  -80.193597
21          Detroit    MI  42.331551  -83.046640
22        Palo Alto    CA  37.444329 -122.159847
23          Chicago    IL  41.875562  -87.624421
24          Amherst    MA  42.373195  -72.519876
25  Charlottesville    VA  38.029306  -78.476678
26           Newark    DE  39.682836  -75.751568
27           Durham    NC  35.996653  -78.901805
28           Boston    MA  42.358834  -71.057830
29       Huntington    WV  38.419250  -82.445154
30       South Bend    IN  41.683381  -86.250007
31           Austin    TX  30.271129  -97.743700
32             Kent    OH  41.151311  -81.357805
33          Atlanta    GA  33.754466  -84.389815
34          Waltham    MA  42.376238  -71.235564
35         New York    NY  40.712728  -74.006015
36        Kalamazoo    MI  42.291707  -85.587229
37     Indianapolis    IN  39.768333  -86.158350

In [9]:
for _, row in locations.iterrows():
    print(f"[[{row['lat']:.6f}, {row['lon']:.6f}], '{row['City']}, {row['State']}'],")

[[38.876933, -77.089309], 'Arlington, VA'],
[[41.661256, -91.529911], 'Iowa City, IA'],
[[33.520682, -86.802433], 'Birmingham, Al'],
[[35.913154, -79.055780], 'Chapel Hill, NC'],
[[39.290882, -76.610759], 'Baltimore, MD'],
[[34.053691, -118.242766], 'Los Angeles, CA'],
[[33.959768, -83.376398], 'Athens, GA'],
[[42.365635, -71.104002], 'Cambridge, MA'],
[[42.437418, -76.548372], 'Ithaca, NY'],
[[41.308214, -72.925052], 'New Haven, CT'],
[[37.870839, -122.272863], 'Berkeley, CA'],
[[39.952724, -75.163526], 'Philadelphia, PA'],
[[29.651968, -82.324985], 'Gainesville, FL'],
[[39.739236, -104.984862], 'Denver, CO'],
[[47.603832, -122.330062], 'Seattle, WA'],
[[43.074690, -89.384166], 'Madison, WI'],
[[40.014986, -105.270545], 'Boulder, CO'],
[[37.787936, -122.407520], 'San Francisco, CA'],
[[38.625406, -90.190009], 'St. Louis, MO'],
[[38.980666, -76.936919], 'College Park, MD'],
[[25.774157, -80.193597], 'Miami, FL'],
[[42.331551, -83.046640], 'Detroit, MI'],
[[37.444329, -122.159847], 'Palo Alto, CA'],
[[41.875562, -87.624421], 'Chicago, IL'],
[[42.373195, -72.519876], 'Amherst, MA'],
[[38.029306, -78.476678], 'Charlottesville, VA'],
[[39.682836, -75.751568], 'Newark, DE'],
[[35.996653, -78.901805], 'Durham, NC'],
[[42.358834, -71.057830], 'Boston, MA'],
[[38.419250, -82.445154], 'Huntington, WV'],
[[41.683381, -86.250007], 'South Bend, IN'],
[[30.271129, -97.743700], 'Austin, TX'],
[[41.151311, -81.357805], 'Kent, OH'],
[[33.754466, -84.389815], 'Atlanta, GA'],
[[42.376238, -71.235564], 'Waltham, MA'],
[[40.712728, -74.006015], 'New York, NY'],
[[42.291707, -85.587229], 'Kalamazoo, MI'],
[[39.768333, -86.158350], 'Indianapolis, IN'],